plugins:
  - eslint-plugin-vue

extends:
  - ../../../.eslintrc.yaml
  - plugin:vue/recommended

env:
  browser: true

rules:
  vue/attributes-order: [0]
  vue/component-definition-name-casing: [0]
  vue/html-closing-bracket-spacing: [0]
  vue/max-attributes-per-line: [0]
  vue/one-component-per-file: [0]
